version: "3"

services:
  mongodb:
    container_name: mongo-antenas
    restart: always
    image: mongo:4.2.9
    env_file:
      - .env
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_MONGODB: ${MONGODB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  app:
    container_name: antenas-app
    restart: always
    build: .
    volumes:
      - .:/usr/app
    ports:
      - "3333:3333"
    depends_on:
      - mongodb
